[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-simple"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 